Update CMake Windows support
ibmruntimes/openj9-openjdk-jdk pull request #281
Opened 2021-02-05 18:25 UTC by dnakamura

- Enable using clang to compile the interpreter
- Update tool wrappers to work with new fixpath

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

2021-02-05 18:27 UTC, dnakamura commented
See also eclipse/openj9#11892

2021-02-05 19:04 UTC, pshipton commented
Are any of these changes needed for jdk16?

2021-02-05 19:06 UTC, pshipton commented
jenkins compile win jdknext

2021-02-05 19:28 UTC, pshipton commented
> Are any of these changes needed for jdk16?

Since the build with https://github.com/eclipse/openj9/pull/11892 failed on jdk16, the answer must be yes.
https://ci.eclipse.org/openj9/job/Build_JDK16_x86-64_windows_cm_Personal/2/

2021-02-05 20:11 UTC, keithc-ca requested changes

2021-02-05 20:11 UTC, keithc-ca commented on closed/autoconf/custom-hook.m4
> +     UTIL_REQUIRE_PROGS([OPENJ9_CLANG], [clang])
nit: please fix indentation (2 spaces per level) to be consistent

2021-02-05 20:11 UTC, keithc-ca commented on closed/autoconf/custom-hook.m4
> +  OPENJ9_GENERATE_TOOL_WRAPPER([clang], [$OPENJ9_CLANG])
Please put these calls in sorted order (like jdk11).

2021-02-05 20:26 UTC, pshipton approved these changes

2021-02-08 18:02 UTC, keithc-ca commented on closed/autoconf/custom-hook.m4
>    OPENJ9_GENERATE_TOOL_WRAPPER([jar], [$JAR])
'jar' comes before 'java'.

2021-02-08 19:51 UTC, keithc-ca approved these changes

2021-02-08 19:53 UTC, keithc-ca commented
> > Are any of these changes needed for jdk16?
> Since the build with [eclipse/openj9#11892](https://github.com/eclipse/openj9/pull/11892) failed on jdk16, the answer must be yes.

@dnakamura Please put together an equivalent change for jdk16.

2021-02-08 19:57 UTC, keithc-ca commented
Jenkins test sanity win,wincm jdknext

2021-02-08 20:29 UTC, keithc-ca commented
Jenkins test sanity wincm jdknext depends eclipse/openj9#11892

2021-02-08 20:49 UTC, keithc-ca requested changes
Apparently changes are required here or in openj9:
```
15:37:50  com\ibm\oti\VMCPTool\Main.java:451: error: cannot find symbol
15:37:50  			return new VirtualMethodRef(e, classes);
15:37:50  			           ^
15:37:50    symbol:   class VirtualMethodRef
15:37:50    location: class Main
```

2021-02-08 21:11 UTC, dnakamura commented
Appears to just be a typo introduced when converting the if statements.

2021-02-08 21:34 UTC, keithc-ca commented
Jenkins test sanity wincm jdknext depends eclipse/openj9#11892

2021-02-09 00:31 UTC, keithc-ca approved these changes

2021-02-09 00:33 UTC, merged