Updates and fixes for z platform
ibmruntimes/openj9-openjdk-jdk pull request #547
Opened 2023-02-07 19:35 UTC by BobMDu

- tokenLabel keyword support
- APAR IJ09107
- Point does not match field size Exception for EC curve

Signed-off-by: Bob Du <bob.du@ibm.com>

2023-02-07 20:37 UTC, pshipton commented
I believe this is the forward port of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/598

2023-02-08 17:44 UTC, keithc-ca requested changes
Please also make the summary of your commit message and this pull request less general.
"Updates and fixes for z platform" doesn't suggest the narrow scope of the actual changes.

2023-02-08 17:44 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11Signature.java
> +        // Check if the public key is EC public key to keep its key size
Please finish each sentence with a period.

2023-02-08 17:44 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11Signature.java
> +            ecKeySize = ((ECPublicKey)publicKey).getParams().getCurve().getField().getFieldSize();
Please use pattern matching:
```java
        if (publicKey instanceof ECPublicKey ecPublicKey) {
            ecKeySize = ecPublicKey.getParams().getCurve().getField().getFieldSize();
```

2023-02-08 17:44 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
> +            if ((slotID < 0) || showInfo|| (tokenLabel != null)) {
Formatting: space both sides of each binary operator (`||`).

2023-02-08 17:44 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
> +                        System.out.println("Slots with tokens: " + toString(slotsWithTokens));
Please minimize the change relative to upstream, i.e. don't introduce a new local variable:
```java
                    slots = p11.C_GetSlotList(true);
                    System.out.println("Slots with tokens: " + toString(slots));
```
The use of `slots` below for Z will be unaffected.

2023-02-08 17:44 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
> +                        } catch (Exception ex) {
What exceptions are you anticipating? Can this be narrowed to catch fewer, more specific exceptions?

2023-02-09 16:58 UTC, BobMDu commented
@keithc-ca I've made changes to address all the items you pointed out. Can you please review again when you have time? Thanks.

2023-02-09 18:40 UTC, keithc-ca requested changes

2023-02-09 18:40 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/Config.java
> +                }
The braces I suggested around this code are required; it doesn't compile without them.

2023-02-09 18:40 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11Signature.java
> +    // Check if running on z platform
Please finish each sentence with a period; here, and on lines 178 and 491.

2023-02-09 18:40 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
> +                        }
Please move `label` into the `try` block; it's not needed elsewhere:
```java
                        try {
                            String label = new String(p11.C_GetTokenInfo(slots[i]).label).trim();
                            if (tokenLabel.equalsIgnoreCase(label)) {
                                slotID = -1;
                                slotListIndex = i;
                                found = true;
                                break;
                            }
                        } catch (PKCS11Exception ex) {
                            // ignore
                        }
```

2023-02-09 18:40 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
> +                    }
I'm not a big fan of redundant variables. The `for` loop above could begin like this:
```java
                    for (int i = 0;; i++) {
                        if (i >= slots.length) {
                            throw new IOException("Invalid Token Label : "
                                    + tokenLabel);
                        }
```
(but I won't insist).

2023-02-09 21:41 UTC, keithc-ca approved these changes

2023-02-09 21:41 UTC, keithc-ca commented
Built locally (with patches to openj9).

2023-02-09 21:42 UTC, merged

2023-02-13 18:22 UTC, BobMDu commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/Config.java
> +                        tokenLabel = parseStringEntry("tokenLabel");
@keithc-ca https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/548

2023-02-13 21:23 UTC, pshipton commented
It seems we could have a release note / What's New in the doc for the "tokenLabel keyword support". @BobMDu if you agree pls open an issue at https://github.com/eclipse-openj9/openj9-docs