Cache Algorithms For CRIU Startup
ibmruntimes/openj9-openjdk-jdk pull request #565
Opened 2023-03-13 16:30 UTC by jasonkatonica

When making use of the CRIU feature for a fast startup it has been found that fetching algorithms is quite slow from the providers installed.

This update saves all algorithms available in all providers prior to a checkpoint being taken. This cache then becomes available for callers after a restore has taken place.

Any updates to the security providers order made via the Security classes triggers the invalidation of this cache.

This update is dependent upon https://github.com/eclipse-openj9/openj9/pull/16888

Signed-off-by: Jason Katonica <katonica@us.ibm.com>

2023-03-13 20:28 UTC, keithc-ca requested changes

2023-03-14 12:26 UTC, jasonkatonica commented on src/java.base/share/classes/java/security/Security.java
> +		System.getProperty("enable.j9internal.checkpoint.security.api.debug", "false"));
Made this update to use `Boolean.getBoolean()`.

2023-03-14 12:27 UTC, jasonkatonica commented on src/java.base/share/classes/java/security/Security.java
> +    /*[ENDIF] CRIU_SUPPORT*/
I added spaces before all `*/` in the file surrounding `CRIU_SUPPORT`

2023-03-16 20:33 UTC, keithc-ca commented on src/java.base/share/classes/java/security/Security.java
> +    /*[ENDIF] CRIU_SUPPORT*/
Our convention is not to include that space in the `/*[IF` line, only in places after the `]`, so combine with my other suggestion, this becomes:
```java
    /*[IF CRIU_SUPPORT]*/
    private static final boolean criuDebug = Boolean.getBoolean("enable.j9internal.checkpoint.security.api.debug");
    /*[ENDIF] CRIU_SUPPORT */
```

2023-03-16 22:12 UTC, keithc-ca requested changes
Please squash.

2023-03-17 10:53 UTC, jasonkatonica commented
Rebased and squashed into single commit.

2023-03-17 17:35 UTC, keithc-ca approved these changes
Will merge assuming testing in https://github.com/eclipse-openj9/openj9/pull/16888 passes.

2023-03-17 19:51 UTC, merged