Copy openj9 config header files after target build-j9
ibmruntimes/openj9-openjdk-jdk pull request #596
Opened 2023-05-02 21:59 UTC by JasonFengJ9

Copy openj9 config header files after target build-j9

Created `openj9_config_header_rules` and target `openj9-config-headers`, and invoke it after `build-j9`.

related
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/592

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

2023-05-03 14:29 UTC, keithc-ca requested changes

2023-05-03 14:29 UTC, keithc-ca commented on closed/OpenJ9.gmk
> +	$(eval $(call openj9_config_header_rules, $(file))))
This an more directly be expressed as
```
$(foreach file, \
	$(CONFIG_HEADERS), \
	$(eval $(call openj9_config_header_rules, $(OPENJ9_VM_BUILD_DIR)/$(file))))
```

2023-05-03 16:21 UTC, JasonFengJ9 commented on closed/OpenJ9.gmk
> +	$(eval $(call openj9_config_header_rules, $(file))))
Updated

2023-05-03 16:21 UTC, JasonFengJ9 commented on closed/OpenJ9.gmk
> +  $(SUPPORT_OUTPUTDIR)/modules_include/java.base/$(notdir $(strip $1)) : $(strip $1)
Removed

2023-05-03 18:44 UTC, keithc-ca commented
Unfortunately, this yields copies of `j9cfg.h` and `omrcfg.h` in the JDK image (which we don't want).

I think we'll need to adjust `CFLAGS_JDKEXE`, `CFLAGS_JDKLIB`, `CXXFLAGS_JDKEXE` and `CXXFLAGS_JDKLIB` to add the necessary `-I` options; that can be done entirely within `custom-spec.gmk.in`:
```
ifeq (true,$(OPENJ9_ENABLE_CMAKE))
  CONFIG_INCLUDES     = $(addprefix -I$$(OUTPUTDIR)/vm/, runtime runtime/omr)
  OPENJ9_VM_BUILD_DIR = $(OUTPUTDIR)/vm/runtime
else
  CONFIG_INCLUDES     = $(addprefix -I$$(OUTPUTDIR)/vm/, include omr/include_core)
  OPENJ9_VM_BUILD_DIR = $(OUTPUTDIR)/vm
endif

# Enable use of j9cfg.h in openjdk native code.
$(foreach var, \
	CFLAGS_JDKEXE CFLAGS_JDKLIB CXXFLAGS_JDKEXE CXXFLAGS_JDKLIB, \
	$(eval $(var) += $(CONFIG_INCLUDES)))
```

2023-05-03 20:12 UTC, keithc-ca commented
After further investigation, I think we need to combine my suggestion above (https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/596#issuecomment-1533529759) with the changes to copy those two files to a new directory. What I proposed breaks UMA builds by creating a conflict with zlib header files (and maybe other things).

2023-05-04 02:27 UTC, JasonFengJ9 commented
Copied `j9cfg.h` & `omrcfg.h` into `$(SUPPORT_OUTPUTDIR)/openj9_include`, and added it to openjdk native includes.

2023-05-04 14:07 UTC, keithc-ca approved these changes

2023-05-04 14:58 UTC, merged