Register natives in ConstantPool init
ibmruntimes/openj9-openjdk-jdk pull request #666
Opened 2023-09-20 19:12 UTC by tajila

Depends on https://github.com/eclipse-openj9/openj9/pull/18169

2023-09-20 19:26 UTC, keithc-ca requested changes

2023-09-20 19:26 UTC, keithc-ca commented on src/java.base/share/classes/jdk/internal/reflect/ConstantPool.java
> -
Please insert the copyright notice before this line instead of replacing it.

2023-09-21 15:18 UTC, keithc-ca approved these changes

2023-09-21 22:54 UTC, keithc-ca commented
Jenkins test sanity zlinux jdknext

2023-09-22 13:22 UTC, tajila commented
Only failures are:

```
FAILED: test_verifyJVMTIMacros
java.lang.AssertionError: JVMTI_VTHREAD_STATE_YIELDING (7) does not match VirtualThread.YIELDING (10)
	at org.testng.Assert.fail(Assert.java:96)
```

unrelated to this PR.

FYI @babsingh

2023-09-22 13:33 UTC, keithc-ca commented
I created https://github.com/eclipse-openj9/openj9/issues/18183 to address the test failure.

2023-09-22 13:34 UTC, merged