Change to use ENDIF rather than ELSE for CRIU_SUPPORT
ibmruntimes/openj9-openjdk-jdk pull request #717
Opened 2024-01-04 02:02 UTC by WilburZjh

The CRIU is enabled by default for the
Linux platforms. That means all the
Linux builds are CRIU. But it need a
command line option to enable it at
runtime if someone wants to use CRIU.

There was an error in our current code.
During the build, the preprocessor
eliminate the code in the [ELSE]
CRIU_SUPPORT. This would cause error if
the --enable-criu-support jvm option
is not enabled in an application. The
application need the logic within [ELSE]
CRIU_SUPPORT. Therefore, we use the
[ENDIF] to replace the [ELSE] in the code.

2024-01-04 04:20 UTC, pshipton commented
This is to fix https://github.com/eclipse-openj9/openj9/issues/18602

2024-01-04 14:44 UTC, keithc-ca requested changes
I think the commit message and the summary here could be improved. Rather than describe *how* the problem was fixed, explain *what* problem is fixed.

2024-01-04 14:44 UTC, keithc-ca commented on src/java.base/unix/classes/sun/security/provider/NativePRNG.java
> +            /*[ENDIF] CRIU_SUPPORT */
Suggest using `return;` after line 510 eliminating the need for `else` and lines 525-527 below.

2024-01-04 15:14 UTC, keithc-ca commented
We'll also want a copy of this (once finalized) for https://github.com/ibmruntimes/openj9-openjdk-jdk22.

2024-01-04 15:42 UTC, WilburZjh commented
> The content looks good, but it doesn't appear that you've addressed my concern about the commit message or the summary here. From my perspective, the essence of this is to restore the behavior (actually read random data) on platforms where CRIU is supported, but not in use.

Yes, I just updated the code. Now Im updating the commit message.

2024-01-04 18:59 UTC, pshipton commented
I see the commit message was updated. Is this ready to be removed from draft state?

2024-01-04 19:02 UTC, WilburZjh commented
> I see the commit message was updated. Is this ready to be removed from draft state?

I rerun the failed tests on the initial code without using the `return`, and the failed tests are passed. Now I am building the JDKs and rerun on the failed cases to ensure that the failed cases are passed.

2024-01-04 21:42 UTC, keithc-ca approved these changes
Approved, assuming testing will be successful.

2024-01-05 13:26 UTC, pshipton commented
The change looked correct so I went ahead and merged it for jdk21 and we started a Semeru 0.42 M3 build, which is looking (very) good.

2024-01-05 13:49 UTC, WilburZjh commented
Build is passed, and the failed cases are passed. Change from draft to ready for review.

@jasonkatonica FYI

2024-01-05 14:01 UTC, pshipton approved these changes

2024-01-05 14:01 UTC, merged