Include LICENSE file when bundling OpenJCEPlus
ibmruntimes/openj9-openjdk-jdk pull request #732
Opened 2024-01-19 16:19 UTC by KostasTsiounis

The `LICENSE` file that is part of the `OpenJCEPlus` open-source project needs to be included in the `OpenJDK`'s legal subdirectory, as well as within the corresponding `jmod`, when said project is bundled.

Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

2024-01-19 17:56 UTC, keithc-ca requested changes

2024-01-19 17:56 UTC, keithc-ca commented on closed/get_j9_source.sh
> +	cp LICENSE src/main/openjceplus/share/legal/OPENJCEPLUS_LICENSE
I think a better place for this is in `closed/custom/modules/openjceplus/Copy.gmk` which would say something like:
```
include $(TOPDIR)/closed/CopySupport.gmk

$(call openj9_copy_files,, \
	$(OPENJCEPLUS_TOPDIR)/LICENSE \
	$(LEGAL_DST_DIR)/OPENJCEPLUS_LICENSE)
```

2024-01-19 19:12 UTC, keithc-ca commented on closed/get_j9_source.sh
> +	cp LICENSE src/main/openjceplus/share/legal/OPENJCEPLUS_LICENSE
Sorry, I meant to refer to `closed/make/modules/openjceplus/Copy.gmk`.

2024-01-19 19:43 UTC, keithc-ca requested changes

2024-01-19 19:43 UTC, keithc-ca commented on closed/get_j9_source.sh
> +# (c) Copyright IBM Corp. 2017, 2024 All Rights Reserved
Please revert this.

2024-01-19 19:43 UTC, keithc-ca commented on closed/make/modules/openjceplus/Copy.gmk
> +	    $(LEGAL_DST_DIR)/OPENJCEPLUS_LICENSE)
Please don't mix spaces and tabs here; just use spaces like the rest of the file.

2024-01-22 19:25 UTC, keithc-ca commented on closed/make/modules/openjceplus/Copy.gmk
> +      $(OPENJCEPLUS_TOPDIR)/NOTICES.md \
This file does not appear to exist in https://github.com/IBM/OpenJCEPlus; that will need to change before this is safe to merge.

2024-01-22 19:39 UTC, keithc-ca commented on closed/make/modules/openjceplus/Copy.gmk
> +      $(OPENJCEPLUS_TOPDIR)/NOTICES.md \
If `NOTICES.md` won't be in the root repository (https://github.com/IBM/OpenJCEPlus), then this should be conditional on the existence of that file, which, based on https://github.com/ibmruntimes/OpenJCEPlus/pull/3, is only expected in that fork.

2024-01-22 21:08 UTC, keithc-ca commented on closed/make/modules/openjceplus/Copy.gmk
> +      $(OPENJCEPLUS_TOPDIR)/NOTICES.md \
This depends on https://github.com/ibmruntimes/OpenJCEPlus/pull/3, which should be merged first.

2024-01-26 19:09 UTC, keithc-ca approved these changes

2024-01-26 19:09 UTC, keithc-ca commented
Jenkins compile alinux jdknext

2024-01-26 19:57 UTC, merged

2024-03-14 19:12 UTC, JinhangZhang commented
Backport to Semeru JDK11 PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/761