Add s390x-linux to platforms bundling OpenJCEPlus
ibmruntimes/openj9-openjdk-jdk pull request #741
Opened 2024-02-06 19:51 UTC by KostasTsiounis

Bundling of `OpenJCEPlus` with the `OpenJDK` is not supported in `s390x-linux` platforms.

Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

2024-02-06 22:00 UTC, keithc-ca requested changes

2024-02-06 22:04 UTC, KostasTsiounis commented on closed/make/modules/openjceplus/Lib.gmk
> +    OPENJCEPLUS_JGSKIT_PLATFORM := s390-linux64
Done.

2024-02-06 22:37 UTC, keithc-ca commented
The description says "not supported"; should it also say "but should be"? Could you clarify, please?

2024-02-07 03:42 UTC, pshipton commented
I hope this isn't something you had wanted to include in the 0.43 release.

2024-02-07 15:12 UTC, KostasTsiounis commented
> The description says "not supported"; should it also say "but should be"? Could you clarify, please?

Sorry. It was a typo. I meant to say in "**now** supported". I fixed it.

2024-02-07 15:12 UTC, KostasTsiounis commented
> I hope this isn't something you had wanted to include in the 0.43 release.

No, it wasn't something we wanted for 0.43.

2024-02-21 22:13 UTC, keithc-ca approved these changes

2024-02-21 22:13 UTC, keithc-ca commented
Jenkins compile zlinux jdknext

2024-02-21 22:55 UTC, merged

2024-02-22 17:18 UTC, KostasTsiounis commented
FYI @keithc-ca

2024-03-14 19:10 UTC, JinhangZhang commented
Backport to Semeru JDK11 PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/761