Initialize VarHandle.methodHandleTable and its entries with atomic CAS
ibmruntimes/openj9-openjdk-jdk pull request #747
Opened 2024-02-26 17:01 UTC by jdmpapin

This prevents double initialization when multiple threads are racing through `getMethodHandle()`. Once a non-null reference has been written to one of these locations, any subsequent write to the same location is a problem for the OpenJ9 JIT given its current handling of known objects.

Issue: eclipse-openj9/openj9#18882

2024-02-26 17:47 UTC, keithc-ca requested changes

2024-02-26 17:47 UTC, keithc-ca commented on src/java.base/share/classes/java/lang/invoke/VarHandle.java
> +            }
Suggest this should use `compareAndExchangeReference()` which avoids an unnecessary access and makes it clear the result is non-null:
```java
            Object other = UNSAFE.compareAndExchangeReference(this, METHOD_HANDLE_TABLE_OFFSET, null, mhTable);
            if (other != null) {
                // We lost the race. Use the winning table instead.
                mhTable = (MethodHandle[])other;
            }
```
Likewise for element access below:
```java
            long offset = Unsafe.ARRAY_OBJECT_BASE_OFFSET + (Unsafe.ARRAY_OBJECT_INDEX_SCALE * mode);
            Object other = UNSAFE.compareAndExchangeReference(mhTable, offset, null, mh);
            if (other != null) {
                // We lost the race. Use the winning table instead.
                mh = (MethodHandle)other;
            }
```

2024-02-26 17:47 UTC, keithc-ca commented on src/java.base/share/classes/java/lang/invoke/VarHandle.java
> +import jdk.internal.misc.Unsafe;
Please put this import with others for jdk.internal.

2024-02-26 17:59 UTC, keithc-ca commented
> a problem for the OpenJ9 JIT given its current handling of known objects

I'm not sure the problem is confined to OpenJ9: the assertion is generated by [InvokerBytecodeGenerator](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/java/lang/invoke/InvokerBytecodeGenerator.java#L720).

2024-02-26 18:07 UTC, jdmpapin commented
Yes, but a subsequent write only causes the assertion to fail because of the way we deal with known objects. Otherwise, we'd have gotten the LF from the MH at runtime and it would match

2024-02-26 18:13 UTC, keithc-ca commented
> Yes, but a subsequent write only causes the assertion to fail because of the way we deal with known objects. Otherwise, we'd have gotten the LF from the MH at runtime and it would match

I'm not sure whether to infer from that response that future changes to OpenJ9 are anticipated which will eliminate the need for this patch.

2024-02-26 18:58 UTC, jdmpapin commented
Yes, we anticipate future OpenJ9 changes will allow this to be reverted, in particular the implementation of https://github.com/eclipse-openj9/openj9/issues/16616. See https://github.com/eclipse-openj9/openj9/issues/18882#issuecomment-1958173709 and https://github.com/eclipse-openj9/openj9/issues/18882#issuecomment-1960277863. It will be some time though. I have some not-yet-contributed partial progress toward it, but none of that is on the code generation / GC interactions, which I expect to be the bulk of the work

2024-02-27 19:31 UTC, jdmpapin commented
Updated to address review comments

2024-02-27 21:45 UTC, keithc-ca commented
Jenkins test sanity.openjdk zlinux jdknext

2024-02-27 21:45 UTC, keithc-ca commented
Jenkins copyright check

2024-02-28 02:39 UTC, keithc-ca commented
The failures seem to only be with respect to `java.lang.Class.toGenericString()` because `sealed` is missing; see https://github.com/eclipse-openj9/openj9/issues/19033.

2024-02-28 02:40 UTC, keithc-ca approved these changes

2024-02-28 02:49 UTC, merged