[FFI] Handling the default library loading on z/OS
ibmruntimes/openj9-openjdk-jdk pull request #794
Opened 2024-05-27 19:11 UTC by ChengJin01

The changes follow the same way of accessing the default
libraries on AIX with the inlined functions in a list to
address the issue with the default libraries during the
FFI downcall on z/OS.

Related: [Internal 441](https://github.ibm.com/runtimes/javanext/issues/441)

Signed-off-by: ChengJin01 <jincheng@ca.ibm.com>

2024-05-27 19:11 UTC, ChengJin01 commented
The PR (verified on AIX) has the same changes as https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/159.

2024-05-27 20:11 UTC, keithc-ca requested changes

2024-05-27 20:27 UTC, ChengJin01 commented on src/java.base/share/classes/jdk/internal/foreign/SystemLookup.java
> +        MemorySegment funcs_addr = funcsLibLookup.find("funcs_addr").orElseThrow();
Fixed as suggested above.

2024-05-27 21:11 UTC, keithc-ca commented
Jenkins test sanity aix,alinux jdknext

2024-05-28 04:39 UTC, ChengJin01 commented
The failure at https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_Personal/37/artifact/Test_openjdknext_j9_sanity.functional_aarch64_linux_Personal_testList_0/37/aqa-tests/TKG/output_17168469728045/Test_openjdknext_j9_sanity.functional_aarch64_linux_Personal_testList_0.tap
```
        Caused by: java.util.NoSuchElementException: Symbol not found: funcs_addr
        	at java.base/java.lang.foreign.SymbolLookup.findOrThrow(SymbolLookup.java:179)
        	at java.base/jdk.internal.foreign.SystemLookup.getInlinedFunctListAddr(SystemLookup.java:98)
        	at java.base/jdk.internal.foreign.SystemLookup.<clinit>(SystemLookup.java:65)
        	... 34 more
        -----------------------------------
        Jep454Tests_testLinkerFfi_DownCall_0_FAILED
```
indicates we should do nothing in `getInlinedFunctListAddr()` on other platforms give `funcs_addr` is specific to AIX & z/OS. So I suggest to add a piece of code to simply return null for non-AIX/zOS platform in the static method as follows:
```
    private static MemorySegment getInlinedFunctListAddr() {
   if (!OperatingSystem.isAix() || !OperatingSystem.isZOS()) {
         return null;
     }
    ....
}
```

2024-05-28 12:39 UTC, keithc-ca commented
> simply return null for non-AIX/zOS platforms

I suggest that should happen within `getInlinedFunctListAddr()` as it already checks for AIX; so moving the definition of `funcsLayout` to the beginning addresses the problem:
```java
        SequenceLayout funcsLayout;

        if (OperatingSystem.isAix()) {
            funcsLayout = AixFuncSymbols.LAYOUT;
        } else if (OperatingSystem.isZOS()) {
            funcsLayout = ZosFuncSymbols.LAYOUT;
        } else {
            return null;
        }
```

2024-05-28 14:32 UTC, keithc-ca commented
Jenkins test sanity aix,alinux jdknext

2024-05-28 19:06 UTC, keithc-ca approved these changes

2024-05-28 19:07 UTC, merged