Update FIPS140-3 exclusions with Windows
ibmruntimes/openj9-openjdk-jdk pull request #831
Opened 2024-08-23 15:21 UTC by JinhangZhang

Add failures shows up in the windows platform.

2024-08-23 18:56 UTC, AdamBrousseau commented
Jenkins line endings check

2024-08-23 18:57 UTC, AdamBrousseau commented
Jenkins copyright check

2024-09-26 18:18 UTC, JinhangZhang commented
@keithc-ca please help to review

2024-09-26 19:26 UTC, keithc-ca requested changes

2024-09-26 19:26 UTC, keithc-ca commented on test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt
> +sun/security/ec/ed/EdDSATest.java https://github.com
The file should end with a newline.

2024-09-26 19:57 UTC, JinhangZhang commented on test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt
> +sun/security/ec/ed/EdDSATest.java https://github.com
added

2024-09-26 21:22 UTC, keithc-ca approved these changes

2024-09-26 21:22 UTC, merged