Enable JFR modules when JFR is enabled
ibmruntimes/openj9-openjdk-jdk pull request #838
Opened 2024-09-06 20:19 UTC by thallium

2024-09-06 20:19 UTC, thallium commented
@tajila FYI

2024-09-09 14:57 UTC, keithc-ca requested changes

2024-09-09 14:57 UTC, keithc-ca commented on closed/custom/common/Modules.gmk
> +		#
Outside a rule, a non-continuation line cannot begin with a tab. Please follow the pattern of lines 45-48:
```
  MODULES_FILTER += \
	jdk.jfr \
	jdk.management.jfr \
	#
```

2024-09-09 15:26 UTC, keithc-ca approved these changes

2024-09-09 15:26 UTC, keithc-ca commented
Jenkins compile amac jdknext

2024-09-09 16:37 UTC, keithc-ca commented
Build aborted: changes in master branch of openj9 require changes that are only in the openj9-staging branch of this repository.
Local builds (both with and without JFR) succeeded with this change applied to the openj9-staging branch.

2024-09-09 16:38 UTC, merged

2024-09-09 19:54 UTC, tajila commented
@thallium please add JDK11, 17, 21, and 23 versions

2024-09-09 20:05 UTC, keithc-ca commented
> @thallium please add JDK11, 17, 21, and 23 versions

Won't that require the metadata files be added like in #833?

2024-09-09 21:02 UTC, tajila commented
> Won't that require the metadata files be added like in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/833?

Yes, I've already requested those files to be added.

2024-09-12 13:08 UTC, keithc-ca commented
@thallium Please confirm that the following are back-ports of this change:
* https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/41
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/194
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/381
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/807

In the future, it would be helpful if you could make such connections as you create pull requests.

2024-09-12 14:08 UTC, thallium commented
Thanks. Yes they are back-ports of this change.