Set AIX executables to have exempt SED status
ibmruntimes/openj9-openjdk-jdk pull request #869
Opened 2024-10-28 17:24 UTC by zl-wang

Customers complained IBM SDK8 has this status, but Semeru Runtimes don't, such that they cannot run Semeru Runtimes on their systems when migrating from IBM SDK8. This is a temporary fix without any other impacts, while we are investigating a complete solution for a larger issue (HugePages are not used for codeCache even though proper -Xlp option is specified).

2024-10-28 17:25 UTC, zl-wang commented
@keithc-ca please review

2024-10-29 18:51 UTC, keithc-ca requested changes
Please fix the commit message. The second line should be blank and following lines should be no more than 72 characters long. See the commit guidelines in [OMR](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines).

Logically, this is incomplete as the `-brwexec_must` linker option should be applied to **all** executables, including those from OpenJ9 (e.g. `jitserver` which is currently not supported on AIX).

2024-10-29 18:54 UTC, keithc-ca commented
> This is a temporary fix without any other impacts, while we are investigating a complete solution for a larger issue (HugePages are not used for codeCache even though proper -Xlp option is specified).

Please create an issue at https://github.com/eclipse-openj9/openj9/issues which describes the larger issue and will serve to track follow-up work to replace this "temporary" fix with a more permanent solution.

2024-10-29 19:02 UTC, zl-wang commented
i have it tracked here half-year ago:  https://github.ibm.com/runtimes/openj9-jit-power/issues/414

2024-10-29 19:10 UTC, keithc-ca commented
We should have a public issue.

2024-10-29 19:52 UTC, zl-wang commented
when we don't have enough resources to make real progresses on the issue any time soon, would you recommend tracking it in GHE instead? at least, that was my motivation.

2024-10-29 20:06 UTC, keithc-ca commented
I can think of no reason why that issue shouldn't be publicly visible.

2024-10-30 12:17 UTC, zl-wang commented
opened here:  https://github.com/eclipse-openj9/openj9/issues/20440

2024-10-31 20:08 UTC, keithc-ca commented
> Please fix the commit message

2024-10-31 23:26 UTC, zl-wang commented
done!

2024-11-01 03:01 UTC, keithc-ca commented
Lines in the body should be no more than 72 characters in length, and the description should not begin with spaces.

See the commit guidelines in [OMR](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines).

Please also correct the spelling of "temporary".

2024-11-01 14:13 UTC, keithc-ca commented
Jenkins test sanity.functional aix,amac jdknext

2024-11-01 19:10 UTC, keithc-ca approved these changes

2024-11-01 19:10 UTC, merged